spring:
  application:
    name: auth-server
#  redis:
#    host: localhost
#    port: 6379
##    password: abc123
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#    timeout: 100ms

server:
  port: 6001

management:
  endpoint:
    health:
      enabled: true